CREATE TABLE TASK (
    ID BIGINT IDENTITY NOT NULL,
    TITLE VARCHAR(50) NOT NULL,
    STATUS TINYINT NOT NULL,
    DETAIL VARCHAR(1000),
    REGISTERED_DATE TIMESTAMP NOT NULL,
    COMPLETED_DATE TIMESTAMP,
    IMPORTANCE TINYINT NOT NULL,
    PERIOD TIMESTAMP NOT NULL,
    UPDATE_DATE TIMESTAMP NOT NULL
);

CREATE TABLE WORK_TIME (
    ID BIGINT IDENTITY NOT NULL,
    TASK_ID BIGINT NOT NULL,
    START_TIME TIMESTAMP NOT NULL,
    END_TIME TIMESTAMP,
    CONSTRAINT WORK_TIME_UK_1 UNIQUE (TASK_ID, START_TIME, END_TIME),
    CONSTRAINT WORK_TIME_FK_1 FOREIGN KEY (TASK_ID) REFERENCES TASK (ID)
);

INSERT INTO TASK VALUES(
    1,
    '週報を書く',
    2,
    NULL,
    TIMESTAMPADD(SQL_TSI_HOUR, -5, CURRENT_TIMESTAMP),
    NULL,
    1,
    TIMESTAMPADD(SQL_TSI_DAY, 1, CURRENT_TIMESTAMP),
    TIMESTAMPADD(SQL_TSI_HOUR, -5, CURRENT_TIMESTAMP)
);

INSERT INTO TASK VALUES(
    2,
    '飲み会出欠を回答する',
    0,
    NULL,
    TIMESTAMPADD(SQL_TSI_HOUR, -5, CURRENT_TIMESTAMP),
    NULL,
    0,
    TIMESTAMPADD(SQL_TSI_WEEK, 1, CURRENT_TIMESTAMP),
    TIMESTAMPADD(SQL_TSI_HOUR, -5, CURRENT_TIMESTAMP)
);

INSERT INTO TASK VALUES(
    3,
    '◯◯テスト仕様書レビュー準備',
    1,
    '◯◯機能のテスト仕様書レビューの準備',
    TIMESTAMPADD(SQL_TSI_HOUR, -5, CURRENT_TIMESTAMP),
    NULL,
    2,
    TIMESTAMPADD(SQL_TSI_HOUR, 2, CURRENT_TIMESTAMP),
    TIMESTAMPADD(SQL_TSI_HOUR, -5, CURRENT_TIMESTAMP)
);

INSERT INTO TASK VALUES(
    4,
    'メールチェック',
    3,
    NULL,
    TIMESTAMPADD(SQL_TSI_HOUR, -5, CURRENT_TIMESTAMP),
    TIMESTAMPADD(SQL_TSI_HOUR, -4, CURRENT_TIMESTAMP),
    0,
    TIMESTAMPADD(SQL_TSI_HOUR, -2, CURRENT_TIMESTAMP),
    TIMESTAMPADD(SQL_TSI_HOUR, -4, CURRENT_TIMESTAMP)
);

INSERT INTO WORK_TIME VALUES(1, 1,TIMESTAMPADD(SQL_TSI_MINUTE, -240, CURRENT_TIMESTAMP),TIMESTAMPADD(SQL_TSI_MINUTE, -220, CURRENT_TIMESTAMP));
INSERT INTO WORK_TIME VALUES(2, 3,TIMESTAMPADD(SQL_TSI_MINUTE, -210, CURRENT_TIMESTAMP),TIMESTAMPADD(SQL_TSI_MINUTE, -100, CURRENT_TIMESTAMP));
INSERT INTO WORK_TIME VALUES(3, 3,TIMESTAMPADD(SQL_TSI_MINUTE, -30, CURRENT_TIMESTAMP),null);
INSERT INTO WORK_TIME VALUES(4, 4,TIMESTAMPADD(SQL_TSI_MINUTE, -290, CURRENT_TIMESTAMP),TIMESTAMPADD(SQL_TSI_MINUTE, -280, CURRENT_TIMESTAMP));
