CREATE TABLE TASK (
    ID BIGINT PRIMARY KEY NOT NULL,
    TITLE VARCHAR(50) NOT NULL,
    STATUS TINYINT NOT NULL,
    DETAIL VARCHAR(1000),
    REGISTERED_DATE TIMESTAMP NOT NULL,
    FINISHED_DATE TIMESTAMP,
    PRIORITY TINYINT NOT NULL,
    IMPORTANCE TINYINT NOT NULL,
    URGENCY TINYINT NOT NULL,
    PERIOD TIMESTAMP NOT NULL
);

CREATE TABLE WORK_TIME (
    TASK_ID BIGINT NOT NULL,
    START_TIME TIMESTAMP NOT NULL,
    END_DATE TIMESTAMP NOT NULL,
    CONSTRAINT WORK_TIME_UK_1 UNIQUE (TASK_ID, START_TIME, END_DATE),
    CONSTRAINT WORK_TIME_FK_1 FOREIGN KEY (TASK_ID) REFERENCES TASK (ID)
);
